export const authConstants = {
  USER_AUTH_REQUEST: "USER_AUTH_REQUEST",
  USER_AUTH_SUCCESS: "USER_AUTH_SUCCESS",
  USER_AUTH_FAILURE: "USER_AUTH_REQUEST",
  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",

  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCCESS: "GET_ALL_PRODUCTS_SUCCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_REQUEST",

  CREATE_NEW_PRODUCT_REQUEST: "CREATE_NEW_PRODUCT_REQUEST",
  CREATE_NEW_PRODUCT_SUCCESS: "CREATE_NEW_PRODUCT_SUCCESS",
  CREATE_NEW_PRODUCT_FAILURE: "CREATE_NEW_PRODUCT_FAILURE",

  DELETE_PRODUCTS_REQUEST: "DELETE_PRODUCTS_REQUEST",
  DELETE_PRODUCTS_SUCCESS: "DELETE_PRODUCTS_SUCCESS",
  DELETE_PRODUCTS_FAILURE: "DELETE_PRODUCTS_FAILURE",
};
